DROP SCHEMA IF EXISTS awgs;
CREATE SCHEMA IF NOT EXISTS awgs DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE awgs;

GRANT USAGE ON awgs.* TO awgs@localhost IDENTIFIED BY 'db4awgs'; 
GRANT ALL PRIVILEGES ON awgs.* TO awgs@localhost;

DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS INSULT;
DROP TABLE IF EXISTS ITEMTYPE;
DROP TABLE IF EXISTS ITEM;

CREATE TABLE ROOM (
	ID int(11) NOT NULL auto_increment,
	USER char(255) NOT NULL,
	ROOM char(255) NOT NULL,
	NICK char(255) NOT NULL,
	CONSTRAINT ROOM_PK PRIMARY KEY (ID),
	CONSTRAINT ROOM_UK UNIQUE KEY (ROOM)
) CHARSET utf8;

CREATE TABLE INSULT (
	ID int(11) NOT NULL auto_increment,
	INSULT char(255) NOT NULL,
	CONTRIBUTOR char(255) NOT NULL,
	DATE timestamp NOT NULL,
	CONSTRAINT INSULT_PK PRIMARY KEY (ID)
) CHARSET utf8;

CREATE TABLE ITEMTYPE (
	ID int(5) NOT NULL auto_increment,
	NAME char(255) NOT NULL,
	DESCRIPTION char(255) NOT NULL,
	CONSTRAINT ITEMTYPE_PK PRIMARY KEY (ID),
	CONSTRAINT ITEMTYPE_UK UNIQUE KEY (NAME)
) CHARSET utf8;

CREATE TABLE ITEM (
  ID char(255) NOT NULL,
  NAME char(255) NOT NULL,
  DESCRIPTION text NOT NULL,
  URL char(255) NOT NULL,
  TYPE int(5) NOT NULL,
  OWNER char(255) NOT NULL,
  LASTUPDATE timestamp NOT NULL,
  CONSTRAINT ITEM_PK PRIMARY KEY  (ID),
  CONSTRAINT ITEM_UK UNIQUE KEY (URL),
  CONSTRAINT ITEM_TYPE_FK FOREIGN KEY (TYPE) REFERENCES ITEMTYPE (ID)
) CHARSET utf8;